import { createContext, useContext, useState, ReactNode } from "react";

type Lang = "ru" | "en";

const translations = {
  ru: {
    // Nav & global
    channels: "Каналы",
    groups: "Группы",
    chats: "Чаты",
    search: "Поиск",
    ai: "AI",
    profile: "Профиль",
    settings: "Настройки",
    marketplace: "Рынок",
    wallet: "Кошелёк",
    inventory: "Инвентарь",
    trades: "Трейды",
    logout: "Выйти из аккаунта",
    loading: "Загрузка...",
    error: "Ошибка",
    save: "Сохранить",
    cancel: "Отмена",
    delete: "Удалить",
    confirm: "Подтвердить",
    back: "Назад",
    close: "Закрыть",
    send: "Отправить",
    yes: "Да",
    no: "Нет",

    // Auth
    welcome: "Добро пожаловать!",
    createAccount: "Создайте аккаунт",
    login: "Войти",
    register: "Зарегистрироваться",
    noAccount: "Нет аккаунта? Зарегистрируйтесь",
    hasAccount: "Уже есть аккаунт? Войдите",
    forgotPassword: "Забыли пароль?",
    resetPassword: "Сбросить пароль",
    resetPasswordDesc: "Введите email для получения ссылки восстановления",
    resetLinkSent: "Ссылка отправлена!",
    resetLinkSentDesc: "Проверьте почту для восстановления пароля",
    newPassword: "Новый пароль",
    setNewPassword: "Установить новый пароль",
    passwordUpdated: "Пароль обновлён",
    passwordUpdatedDesc: "Теперь вы можете войти с новым паролем",
    fillAllFields: "Пожалуйста, заполните все поля",
    passwordMinLength: "Пароль должен содержать минимум 6 символов",
    loginError: "Ошибка входа",
    wrongCredentials: "Неверный email или пароль",
    emailNotConfirmed: "Email не подтверждён",
    checkEmailConfirm: "Проверьте почту и подтвердите регистрацию",
    registerError: "Ошибка регистрации",
    alreadyRegistered: "Этот email уже зарегистрирован",
    registerSuccess: "Успешная регистрация!",
    checkEmailToConfirm: "Проверьте почту для подтверждения аккаунта",
    accountBanned: "Аккаунт заблокирован",
    accountBannedDesc: "Ваш аккаунт был заблокирован администратором. Если вы считаете, что это ошибка, обратитесь в поддержку.",
    email: "Email",
    password: "Пароль",

    // Search
    searchPlaceholder: "Поиск людей и каналов...",

    // Direct messages
    directMessages: "Личные сообщения",
    noMessages: "Нет сообщений",
    findPeople: "Найдите человека в поиске!",
    startConversation: "Начните разговор!",
    writeMessage: "Написать сообщение...",
    deleteChat: "Удалить чат",
    deleteAndBlock: "Удалить и заблокировать",
    chatDeleted: "Чат удалён",
    userBlocked: "заблокирован",
    voiceMessage: "Голосовое сообщение",
    forwardMessage: "Переслать сообщение",
    forwardedFrom: "Переслано от",
    selectChat: "Выберите чат:",
    forwarded: "Сообщение переслано",
    reply: "Ответ",
    message: "Сообщение",
    missedCall: "Пропущенный вызов",
    user: "Пользователь",
    blocked: "Вы заблокированы этим пользователем",
    userUnblocked: "Пользователь разблокирован",
    userBlockedAction: "Пользователь заблокирован",
    sendFailed: "Не удалось отправить",
    callFailed: "Не удалось начать вызов",
    typing: "печатает...",

    // Language
    language: "Язык",
    russian: "Русский",
    english: "English",

    // Profile
    displayName: "Отображаемое имя",
    displayNamePlaceholder: "Как вас зовут?",
    aboutMe: "О себе",
    aboutMePlaceholder: "Расскажите о себе...",
    accountCreated: "Аккаунт создан",
    steamIntegration: "Steam интеграция",
    steamRequired: "Необходим для покупки/продажи на маркетплейсе",
    adminPanel: "Панель администратора",
    backToProfile: "← Назад к профилю",
    usernameTaken: "Этот @username уже занят",
    inventoryVisibility: "Видимость инвентаря",

    // AI
    newChat: "Новый чат",
    chatHistory: "История чатов",
    askOrDraw: "Спросите или попросите нарисовать...",
    helloFlame: "Привет! Я FLAME AI",
    aiHint: "Задайте мне вопрос, отправьте фото для анализа или попросите сгенерировать изображение!",
    thinking: "Думаю...",
    imageGeneration: "Генерация изображения...",

    // Marketplace
    marketplaceTitle: "Маркетплейс",
    sell: "Продать",
    buy: "Купить",
    price: "Цена",
    priceUsd: "Цена (USD)",
    newItem: "Новый товар",
    noItems: "Нет товаров",
    beFirstToSell: "Будьте первым — выставьте скин на продажу!",
    sellItem: "Продать товар",
    steamMarketLink: "Ссылка Steam Market",
    steamLinkHint: "Вставьте ссылку — название и цена подтянутся автоматически",
    itemName: "Название",
    description: "Описание",
    image: "Изображение",
    commissionHint: "При продаже удерживается комиссия",
    commissionPercent: "5%",
    listForSale: "Выставить на продажу",
    publishing: "Публикация...",
    itemListed: "Товар выставлен!",
    commissionOnSale: "Комиссия 5% будет удержана при продаже.",
    skinRecognized: "Скин распознан!",
    suggestedAvgPrice: "Средняя рыночная цена. Вы можете указать свою.",
    buyFor: "Купить за",
    removeFromSale: "Снять с продажи",
    itemRemoved: "Товар снят с продажи",
    removeConfirm: "Снять товар с продажи?",
    purchaseComplete: "Покупка завершена!",
    addedToInventory: "Предмет добавлен в инвентарь.",
    insufficientFunds: "Недостаточно средств",
    needAmount: "Нужно",
    youHave: "у вас",
    cantBuyOwn: "Нельзя купить свой товар",
    steamUrlNotSet: "Steam Trade URL не указан",
    addSteamUrlProfile: "Добавьте его в профиле для покупки и продажи",
    addSteamUrlToSell: "Добавьте его в профиле для продажи",
    addSteamUrlToList: "Укажите Steam Trade URL в профиле для выставления товаров",
    enterCorrectPrice: "Укажите корректную цену",
    failedToCreate: "Не удалось создать",
    balance: "Баланс",
    seller: "Продавец",
    commission: "Комиссия",
    buyConfirm: "Купить",
    buyConfirmMessage: "Комиссия 5% будет удержана.",

    // Wallet
    exchange: "FLAME Exchange",
    portfolio: "Портфель (USD)",
    updateEvery10s: "Обновление каждые 10 сек",
    deposit: "Депозит",
    withdraw: "Вывод",
    swap: "Swap",
    marketLive: "Рынок — Live",
    topUp: "Пополнить баланс",
    selectCoinDeposit: "Выберите монету для пополнения:",
    minDeposit: "Минимальный депозит",
    createRequest: "Создать заявку",
    sending: "Отправка...",
    requestCreated: "Заявка создана",
    sendCryptoToAddress: "Отправьте крипто на указанный адрес.",
    withdrawal: "Вывод средств",
    available: "Доступно",
    cryptoWalletAddress: "Адрес крипто-кошелька",
    minWithdrawal: "Минимальный вывод",
    securityPin: "PIN-код (6 цифр)",
    withdrawBtn: "Вывести",
    withdrawRequestCreated: "Заявка на вывод создана",
    withdrawAfterReview: "Средства будут отправлены после проверки.",
    enterAmount: "Введите сумму",
    enterWalletAddress: "Введите адрес крипто-кошелька",
    enter6DigitPin: "Введите 6-значный PIN-код",
    youGive: "Отдаёте",
    youReceive: "Получаете",
    value: "Стоимость",
    commissionFee: "Комиссия (1%)",
    totalReceive: "Итого получите",
    swapBtn: "Обменять",
    swapDone: "Swap выполнен",
    depositAddress: "Адрес для депозита",
    sendOnly: "Отправляйте только",
    network: "Сеть",

    // Social feed
    posts: "Посты",
    newPost: "Новый пост",
    addCaption: "Добавьте подпись...",
    postPublished: "Пост опубликован!",
    noPosts: "Нет постов",
    like: "Нравится",
    comment: "Комментарий",
    comments: "Комментарии",
    writeComment: "Написать комментарий...",
    postDeleted: "Пост удалён",

    // User profile
    sendGift: "Подарок",
    proposeTrade: "Трейд",
    buySkins: "Купить скины",
    forSale: "В продаже",
    inventoryTab: "Инвентарь",
    postsTab: "Посты",
    privateInventory: "Инвентарь скрыт",
    noItemsForSale: "Нет товаров в продаже",
  },
  en: {
    // Nav & global
    channels: "Channels",
    groups: "Groups",
    chats: "Chats",
    search: "Search",
    ai: "AI",
    profile: "Profile",
    settings: "Settings",
    marketplace: "Market",
    wallet: "Wallet",
    inventory: "Inventory",
    trades: "Trades",
    logout: "Sign Out",
    loading: "Loading...",
    error: "Error",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    confirm: "Confirm",
    back: "Back",
    close: "Close",
    send: "Send",
    yes: "Yes",
    no: "No",

    // Auth
    welcome: "Welcome!",
    createAccount: "Create an account",
    login: "Sign In",
    register: "Sign Up",
    noAccount: "Don't have an account? Sign Up",
    hasAccount: "Already have an account? Sign In",
    forgotPassword: "Forgot password?",
    resetPassword: "Reset Password",
    resetPasswordDesc: "Enter your email to receive a recovery link",
    resetLinkSent: "Link sent!",
    resetLinkSentDesc: "Check your email for the recovery link",
    newPassword: "New Password",
    setNewPassword: "Set New Password",
    passwordUpdated: "Password updated",
    passwordUpdatedDesc: "You can now sign in with your new password",
    fillAllFields: "Please fill in all fields",
    passwordMinLength: "Password must be at least 6 characters",
    loginError: "Login error",
    wrongCredentials: "Invalid email or password",
    emailNotConfirmed: "Email not confirmed",
    checkEmailConfirm: "Check your email and confirm registration",
    registerError: "Registration error",
    alreadyRegistered: "This email is already registered",
    registerSuccess: "Registration successful!",
    checkEmailToConfirm: "Check your email to confirm your account",
    accountBanned: "Account Banned",
    accountBannedDesc: "Your account has been banned by an administrator. If you believe this is a mistake, contact support.",
    email: "Email",
    password: "Password",

    // Search
    searchPlaceholder: "Search people and channels...",

    // Direct messages
    directMessages: "Direct Messages",
    noMessages: "No messages",
    findPeople: "Find someone in search!",
    startConversation: "Start a conversation!",
    writeMessage: "Write a message...",
    deleteChat: "Delete chat",
    deleteAndBlock: "Delete & Block",
    chatDeleted: "Chat deleted",
    userBlocked: "blocked",
    voiceMessage: "Voice message",
    forwardMessage: "Forward message",
    forwardedFrom: "Forwarded from",
    selectChat: "Select chat:",
    forwarded: "Message forwarded",
    reply: "Reply",
    message: "Message",
    missedCall: "Missed call",
    user: "User",
    blocked: "You are blocked by this user",
    userUnblocked: "User unblocked",
    userBlockedAction: "User blocked",
    sendFailed: "Failed to send",
    callFailed: "Failed to start call",
    typing: "typing...",

    // Language
    language: "Language",
    russian: "Русский",
    english: "English",

    // Profile
    displayName: "Display Name",
    displayNamePlaceholder: "What's your name?",
    aboutMe: "About Me",
    aboutMePlaceholder: "Tell about yourself...",
    accountCreated: "Account created",
    steamIntegration: "Steam Integration",
    steamRequired: "Required for marketplace buy/sell",
    adminPanel: "Admin Panel",
    backToProfile: "← Back to profile",
    usernameTaken: "This @username is taken",
    inventoryVisibility: "Inventory Visibility",

    // AI
    newChat: "New Chat",
    chatHistory: "Chat History",
    askOrDraw: "Ask or request an image...",
    helloFlame: "Hello! I'm FLAME AI",
    aiHint: "Ask me a question, send a photo for analysis, or request an image!",
    thinking: "Thinking...",
    imageGeneration: "Generating image...",

    // Marketplace
    marketplaceTitle: "Marketplace",
    sell: "Sell",
    buy: "Buy",
    price: "Price",
    priceUsd: "Price (USD)",
    newItem: "New Item",
    noItems: "No items",
    beFirstToSell: "Be the first — list a skin for sale!",
    sellItem: "Sell Item",
    steamMarketLink: "Steam Market Link",
    steamLinkHint: "Paste a link — name and price will auto-fill",
    itemName: "Name",
    description: "Description",
    image: "Image",
    commissionHint: "A commission is deducted on sale",
    commissionPercent: "5%",
    listForSale: "List for Sale",
    publishing: "Publishing...",
    itemListed: "Item listed!",
    commissionOnSale: "5% commission will be deducted on sale.",
    skinRecognized: "Skin recognized!",
    suggestedAvgPrice: "Average market price. You can set your own.",
    buyFor: "Buy for",
    removeFromSale: "Remove from sale",
    itemRemoved: "Item removed from sale",
    removeConfirm: "Remove item from sale?",
    purchaseComplete: "Purchase complete!",
    addedToInventory: "Item added to inventory.",
    insufficientFunds: "Insufficient funds",
    needAmount: "Need",
    youHave: "you have",
    cantBuyOwn: "Cannot buy your own item",
    steamUrlNotSet: "Steam Trade URL not set",
    addSteamUrlProfile: "Add it in your profile for buying and selling",
    addSteamUrlToSell: "Add it in your profile to sell",
    addSteamUrlToList: "Set Steam Trade URL in your profile to list items",
    enterCorrectPrice: "Enter a valid price",
    failedToCreate: "Failed to create",
    balance: "Balance",
    seller: "Seller",
    commission: "Commission",
    buyConfirm: "Buy",
    buyConfirmMessage: "5% commission will be deducted.",

    // Wallet
    exchange: "FLAME Exchange",
    portfolio: "Portfolio (USD)",
    updateEvery10s: "Updates every 10 sec",
    deposit: "Deposit",
    withdraw: "Withdraw",
    swap: "Swap",
    marketLive: "Market — Live",
    topUp: "Top Up Balance",
    selectCoinDeposit: "Select a coin for deposit:",
    minDeposit: "Minimum deposit",
    createRequest: "Create Request",
    sending: "Sending...",
    requestCreated: "Request created",
    sendCryptoToAddress: "Send crypto to the address shown.",
    withdrawal: "Withdrawal",
    available: "Available",
    cryptoWalletAddress: "Crypto wallet address",
    minWithdrawal: "Minimum withdrawal",
    securityPin: "PIN code (6 digits)",
    withdrawBtn: "Withdraw",
    withdrawRequestCreated: "Withdrawal request created",
    withdrawAfterReview: "Funds will be sent after review.",
    enterAmount: "Enter amount",
    enterWalletAddress: "Enter crypto wallet address",
    enter6DigitPin: "Enter 6-digit PIN code",
    youGive: "You give",
    youReceive: "You receive",
    value: "Value",
    commissionFee: "Commission (1%)",
    totalReceive: "Total receive",
    swapBtn: "Swap",
    swapDone: "Swap completed",
    depositAddress: "Deposit address",
    sendOnly: "Send only",
    network: "Network",

    // Social feed
    posts: "Posts",
    newPost: "New Post",
    addCaption: "Add a caption...",
    postPublished: "Post published!",
    noPosts: "No posts",
    like: "Like",
    comment: "Comment",
    comments: "Comments",
    writeComment: "Write a comment...",
    postDeleted: "Post deleted",

    // User profile
    sendGift: "Gift",
    proposeTrade: "Trade",
    buySkins: "Buy Skins",
    forSale: "For Sale",
    inventoryTab: "Inventory",
    postsTab: "Posts",
    privateInventory: "Inventory is private",
    noItemsForSale: "No items for sale",
  },
} as const;

type TranslationKey = keyof typeof translations.ru;

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const saved = localStorage.getItem("flame_lang");
    if (saved === "en" || saved === "ru") return saved;
    return navigator.language.startsWith("en") ? "en" : "ru";
  });

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("flame_lang", l);
  };

  const t = (key: TranslationKey): string => translations[lang][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
